apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alber\Desktop\java-microservices-schelfi\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: visualizer
  name: visualizer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: visualizer
    spec:
      containers:
      - image: bretfisher/visualizer:latest
        name: visualizer
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: "268435456"
          requests:
            cpu: 100m
            memory: "134217728"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: visualizer-claim0
      restartPolicy: Always
      volumes:
      - name: visualizer-claim0
        persistentVolumeClaim:
          claimName: visualizer-claim0
status: {}
