apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\alber\Desktop\java-microservices-schelfi\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: visualizer
  name: visualizer
spec:
  ports:
  - name: "38080"
    port: 38080
    targetPort: 8080
  selector:
    io.kompose.service: visualizer
status:
  loadBalancer: {}
